<?php

return [
    'type'=>[
        'public',
        'private',
        'protected'
    ],
    'status'=>[
        'pending',
        'confirmed',
        'processing',
        'on-hold',
        'completed',
        'rejected',
    ],
    'sub_status'=>[
        'accept',
        'decline'
    ],
    'payment_type'=>[
        'full',
        'partial'
    ],
    'payment_status'=>[
        'paid',
        'partially_paid',
        'unpaid'
    ],
    'skills'=>[
        ''
    ]
];
